name: bee_catalog

description: "Aplicativo Flutter para catálogo de abelhas brasileiras."

# Impede que o projeto seja publicado acidentalmente no pub.dev.
publish_to: 'none'

# Versão atual do aplicativo.
version: 1.0.0+1

# Define a versão mínima do Dart utilizada pelo projeto.
environment:
  sdk: ^3.13.2

# Dependências utilizadas pelo aplicativo.
dependencies:

  # SDK principal do Flutter.
  flutter:
    sdk: flutter

  # Biblioteca de ícones no estilo iOS.
  cupertino_icons: ^1.0.8

# Dependências utilizadas durante o desenvolvimento e testes.
dev_dependencies:

  # Ferramentas de teste do Flutter.
  flutter_test:
    sdk: flutter

  # Regras recomendadas para manter
  # boas práticas no código Dart/Flutter.
  flutter_lints: ^6.0.0

# Configurações específicas do Flutter.
flutter:

  # Permite utilizar os ícones
  # padrão do Material Design.
  uses-material-design: true

  # Informa ao Flutter onde estão
  # armazenadas as imagens do aplicativo.
  assets:
    - assets/images/